modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Coloured-Tooltips/issues"
license="LGPL v2.1"

[[mods]]
modId="colouredtooltips"
updateJSONURL="https://updates.blamejared.com/get?n=colouredtooltips&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.colouredtooltips]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.colouredtooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="CLIENT"