modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Coloured-Tooltips/issues"

[[mods]]
modId="colouredtooltips"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.colouredtooltips]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.colouredtooltips]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="CLIENT"